import type { MockApplication } from "@/src/types/application";

export const mockApplications = [
  {
    id: "miro-frontend-developer",
    slug: "miro-frontend-developer",
    initials: "MI",
    role: "Frontend Developer",
    company: "Miro",
    status: "Wishlist",
    matchScore: 86,
    location: "Remote",
    workMode: "Remote",
    employmentType: "Full-time",
    appliedDate: "May 22, 2026",
    appliedAgo: "2 days ago",
    updatedAt: "May 22",
    source: "LinkedIn",
    deadline: "June 12, 2026",
    applicationUrl: "https://example.com/jobs/miro-frontend-developer",
    skills: ["TypeScript", "React", "Accessibility", "CSS"],
    description: "Build collaborative frontend experiences for Miro using React and TypeScript, with a focus on performance, accessibility, and reusable interface systems.",
  },
  {
    id: "spotify-web-engineer",
    slug: "spotify-web-engineer",
    initials: "SP",
    role: "Web Engineer",
    company: "Spotify",
    status: "Wishlist",
    matchScore: 81,
    location: "Stockholm, Sweden",
    workMode: "Hybrid",
    employmentType: "Full-time",
    appliedDate: "May 21, 2026",
    appliedAgo: "3 days ago",
    updatedAt: "May 21",
    source: "Company website",
    deadline: "June 15, 2026",
    applicationUrl: "https://example.com/jobs/spotify-web-engineer",
    skills: ["JavaScript", "React", "Web Performance", "Testing"],
    description: "Help Spotify deliver fast, inclusive web experiences by contributing to frontend architecture, shared components, experimentation, and product quality.",
  },
  {
    id: "getir-junior-react-developer",
    slug: "getir-junior-react-developer",
    initials: "GE",
    role: "Junior React Developer",
    company: "Getir",
    status: "Applied",
    matchScore: 91,
    location: "Istanbul, Türkiye",
    workMode: "Hybrid",
    employmentType: "Full-time",
    appliedDate: "May 14, 2026",
    appliedAgo: "10 days ago",
    updatedAt: "May 20",
    source: "LinkedIn",
    deadline: "June 5, 2026",
    applicationUrl: "https://example.com/jobs/getir-junior-react-developer",
    skills: ["TypeScript", "React", "React Native", "REST APIs"],
    description: "Develop customer-facing commerce experiences at Getir, working with React, TypeScript, APIs, testing tools, and a cross-functional product team.",
  },
  {
    id: "atlassian-junior-engineer",
    slug: "atlassian-junior-engineer",
    initials: "AT",
    role: "Junior Engineer",
    company: "Atlassian",
    status: "Applied",
    matchScore: 82,
    location: "Remote",
    workMode: "Remote",
    employmentType: "Full-time",
    appliedDate: "May 16, 2026",
    appliedAgo: "8 days ago",
    updatedAt: "May 18",
    source: "Company website",
    deadline: "June 8, 2026",
    applicationUrl: "https://example.com/jobs/atlassian-junior-engineer",
    skills: ["Java", "TypeScript", "React", "Distributed Systems"],
    description: "Join an Atlassian product team to ship dependable collaboration features, learn scalable engineering practices, and contribute across frontend and backend services.",
  },
  {
    id: "trendyol-software-engineer",
    slug: "trendyol-software-engineer",
    initials: "TR",
    role: "Software Engineer",
    company: "Trendyol",
    status: "Applied",
    matchScore: 77,
    location: "Istanbul, Türkiye",
    workMode: "Hybrid",
    employmentType: "Full-time",
    appliedDate: "May 17, 2026",
    appliedAgo: "7 days ago",
    updatedAt: "May 17",
    source: "LinkedIn",
    deadline: "June 10, 2026",
    applicationUrl: "https://example.com/jobs/trendyol-software-engineer",
    skills: ["Java", "Spring Boot", "PostgreSQL", "Kafka"],
    description: "Build scalable commerce services at Trendyol using modern backend practices, event-driven architecture, relational data, and collaborative delivery workflows.",
  },
  {
    id: "insider-junior-web-developer",
    slug: "insider-junior-web-developer",
    initials: "IN",
    role: "Junior Web Developer",
    company: "Insider",
    status: "Assessment",
    matchScore: 79,
    location: "Istanbul, Türkiye",
    workMode: "On-site",
    employmentType: "Full-time",
    appliedDate: "May 18, 2026",
    appliedAgo: "6 days ago",
    updatedAt: "May 19",
    source: "LinkedIn",
    deadline: "June 7, 2026",
    applicationUrl: "https://example.com/jobs/insider-junior-web-developer",
    skills: ["JavaScript", "React", "HTML", "CSS"],
    description: "Create responsive web products for Insider customers while collaborating with designers and engineers on reusable UI, browser quality, and performance.",
  },
  {
    id: "booking-software-engineer-intern",
    slug: "booking-software-engineer-intern",
    initials: "BK",
    role: "Software Engineer Intern",
    company: "Booking.com",
    status: "Assessment",
    matchScore: 84,
    location: "Amsterdam, Netherlands",
    workMode: "Hybrid",
    employmentType: "Internship",
    appliedDate: "May 16, 2026",
    appliedAgo: "8 days ago",
    updatedAt: "May 16",
    source: "University careers",
    deadline: "June 1, 2026",
    applicationUrl: "https://example.com/jobs/booking-software-engineer-intern",
    skills: ["Java", "React", "SQL", "Git"],
    description: "Work with Booking.com engineers on production travel experiences, supported by mentorship, code reviews, testing, and practical software delivery.",
  },
  {
    id: "kron-full-stack-intern",
    slug: "kron-full-stack-intern",
    initials: "KR",
    role: "Full Stack Intern",
    company: "Kron",
    status: "Interview",
    matchScore: 88,
    location: "Istanbul, Türkiye",
    workMode: "Hybrid",
    employmentType: "Internship",
    appliedDate: "July 8, 2026",
    appliedAgo: "12 days ago",
    updatedAt: "May 20",
    source: "LinkedIn",
    deadline: "July 28, 2026",
    applicationUrl: "https://example.com/jobs/kron-full-stack-intern",
    skills: ["TypeScript", "React", "Next.js", "Node.js", "PostgreSQL", "REST APIs", "Git", "Docker"],
    description: "Kron is seeking a Full Stack Intern to help build reliable enterprise software across modern React interfaces and Node.js services. The role combines hands-on product development, mentorship, code reviews, and collaboration with an experienced engineering team.",
  },
  {
    id: "canva-frontend-engineer",
    slug: "canva-frontend-engineer",
    initials: "CA",
    role: "Frontend Engineer",
    company: "Canva",
    status: "Interview",
    matchScore: 85,
    location: "Remote",
    workMode: "Remote",
    employmentType: "Full-time",
    appliedDate: "May 15, 2026",
    appliedAgo: "9 days ago",
    updatedAt: "May 15",
    source: "Company website",
    deadline: "June 2, 2026",
    applicationUrl: "https://example.com/jobs/canva-frontend-engineer",
    skills: ["TypeScript", "React", "Design Systems", "Testing"],
    description: "Build intuitive creative tools at Canva by contributing to performant React interfaces, accessible design systems, and quality-focused frontend engineering.",
  },
  {
    id: "peak-frontend-intern",
    slug: "peak-frontend-intern",
    initials: "PE",
    role: "Frontend Intern",
    company: "Peak",
    status: "Offer",
    matchScore: 93,
    location: "Istanbul, Türkiye",
    workMode: "On-site",
    employmentType: "Internship",
    appliedDate: "May 11, 2026",
    appliedAgo: "13 days ago",
    updatedAt: "May 14",
    source: "Referral",
    deadline: "May 30, 2026",
    applicationUrl: "https://example.com/jobs/peak-frontend-intern",
    skills: ["JavaScript", "React", "CSS", "Git"],
    description: "Support Peak product teams by building polished web interfaces, learning frontend architecture, and shipping improvements with experienced engineers.",
  },
  {
    id: "amazon-software-development-intern",
    slug: "amazon-software-development-intern",
    initials: "AZ",
    role: "Software Development Intern",
    company: "Amazon",
    status: "Rejected",
    matchScore: 74,
    location: "Berlin, Germany",
    workMode: "On-site",
    employmentType: "Internship",
    appliedDate: "May 8, 2026",
    appliedAgo: "16 days ago",
    updatedAt: "May 12",
    source: "Company website",
    deadline: "May 24, 2026",
    applicationUrl: "https://example.com/jobs/amazon-software-development-intern",
    skills: ["Java", "Algorithms", "Data Structures", "AWS"],
    description: "Contribute to an Amazon engineering team by designing, implementing, and testing customer-focused software under the guidance of experienced developers.",
  },
  {
    id: "wise-junior-full-stack-engineer",
    slug: "wise-junior-full-stack-engineer",
    initials: "WI",
    role: "Junior Full Stack Engineer",
    company: "Wise",
    status: "Rejected",
    matchScore: 78,
    location: "Tallinn, Estonia",
    workMode: "Hybrid",
    employmentType: "Full-time",
    appliedDate: "May 7, 2026",
    appliedAgo: "17 days ago",
    updatedAt: "May 10",
    source: "LinkedIn",
    deadline: "May 28, 2026",
    applicationUrl: "https://example.com/jobs/wise-junior-full-stack-engineer",
    skills: ["Java", "React", "SQL", "REST APIs"],
    description: "Help Wise improve international money products across web interfaces and backend services while learning reliable financial software practices.",
  },
] as const satisfies readonly MockApplication[];

export function getMockApplicationBySlug(
  slug: string,
): MockApplication | undefined {
  return mockApplications.find((application) => application.slug === slug);
}

export function getMockApplicationsBySlugs(
  slugs: readonly string[],
): MockApplication[] {
  return slugs.flatMap((slug) => {
    const application = getMockApplicationBySlug(slug);
    return application ? [application] : [];
  });
}
